# Generated by Django 5.2.10 on 2026-01-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('skipped', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CareSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('water', 'Полив'), ('fertilize', 'Подкормка'), ('mist', 'Опрыскивание'), ('repot', 'Пересадка'), ('prune', 'Обрезка')], max_length=20)),
                ('frequency_days', models.PositiveIntegerField(help_text='Каждые N дней (например: 7)')),
                ('last_performed', models.DateTimeField(blank=True, null=True)),
                ('next_due', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Расписание ухода',
                'verbose_name_plural': 'Расписания ухода',
            },
        ),
    ]
