# Generated by Django 5.2.10 on 2026-01-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='Как ты называешь это растение', max_length=100)),
                ('location_at_home', models.CharField(blank=True, help_text='Где стоит (например: Гостиная, южное окно)', max_length=100)),
                ('acquired_date', models.DateField(blank=True, null=True)),
                ('pot_size_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Показывать ли в публичном профиле')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin_name', models.CharField(max_length=200, unique=True)),
                ('common_names', models.CharField(blank=True, help_text='Народные названия через запятую', max_length=500)),
                ('care_profile', models.JSONField(default=dict, help_text='Пример: {"light": "bright", "water": "moderate", "temp": "18-25"}')),
                ('difficulty', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, help_text='Сложность ухода (1-легко, 5-сложно)')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Вид растения',
                'verbose_name_plural': 'Виды растений',
                'ordering': ['latin_name'],
            },
        ),
    ]
